name: Build LaTeX document and other outputs
on: [release]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
      - uses: actions/upload-artifact@master
        with:
          name: print-pdf
          path: main.pdf

  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - uses: docker://pandoc/core:2.19.2
        with:
          args: >-
            --standalone main.tex
            --from latex
            --to epub
            --output output/book.epub
      - uses: actions/upload-artifact@master
        with:
          name: ebook-epub
          path: output
